version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - fastapi_db_url=postgres
      - fastapi_db_port=5432
      - fastapi_db_user=postgres
      - fastapi_db_password=password123
      - fastapi_db_name=fastapi
      - fastapi_SECRET_KEY=3ae90d9094fae6cd8f7d16ab3cb2fb300866080cba5c01601ab5cf0caf296541
      - fastapi_ACCESS_TOKEN_ALGORITHM=HS256
      - fastapi_ACCESS_TOKEN_TTL=60

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
