name: Build and Deploy Code

on: [push, pull_request]

jobs:
  myjob:
    runs-on: ubuntu-latest
    env:
      fastapi_db_url: ${{ secrets.FASTAPI_DB_URL }}
      fastapi_db_port: ${{ secrets.FASTAPI_DB_PORT }}
      fastapi_db_user: ${{ secrets.FASTAPI_DB_USER }}
      fastapi_db_password: ${{ secrets.FASTAPI_DB_PASSWORD }}
      fastapi_db_name: ${{ secrets.FASTAPI_DB_NAME }}
      fastapi_SECRET_KEY: ${{ secrets.FASTAPI_SECRET_KEY }}
      fastapi_ACCESS_TOKEN_ALGORITHM: ${{ secrets.FASTAPI_ACCESS_TOKEN_ALGORITHM }}
      fastapi_ACCESS_TOKEN_TTL: ${{ secrets.FASTAPI_ACCESS_TOKEN_TTL }}
    steps:
      - name: setup postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: "11" # See https://hub.docker.com/_/postgres for available versions
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Install Python version 3.9
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pytest
      - run: echo "🍏 This job's status is ${{ job.status }}."
